### ISSUE TITLE
Incorrect use in Docker?

### ISSUE THREAD

**Issue by zoushucai** [ganuonglachanh/flarum-sonic#13]
Hello, can you explain how this plugin is used in Docker? I use [https://github.com/RikoDEV/flarum-docker](https://github.com/RikoDEV/flarum-docke),  It was built, but there was an error accessing it in the Docker. 
I have made some improvements and added a tool mainly for connecting to the network. 
```bash
apk add --no-progress --no-cache netcat-openbsd nmap socat busybox-extras
```
I am able to access `sonic ` in the flarum container, indicating that I should be able to access it correctly. IP:1491, where IP is the sonic container's IP, The testing is as follows:
```bash
/flarum/app # nmap -p 1491 192.168.128.5
Starting Nmap 7.93 ( https://nmap.org ) at 2023-08-11 23:59 UTC
Nmap scan report for sonic.app0_flarum_network (192.168.128.5)
Host is up (0.000048s latency).

PORT     STATE SERVICE
1491/tcp open  anynetgateway
MAC Address: 02:42:C0:A8:80:05 (Unknown)
/flarum/app # nc -v 192.168.128.5 1491
192.168.128.5 (192.168.128.5:1491) open
CONNECTED <sonic-server v1.4.0>
^Z[1]+  Stopped                    nc -v 192.168.128.5 1491

```
But when I run the following code, it will cause an error, which I don't quite understand,

```bash
/flarum/app # php flarum sonic:addtoindex
Starting...
Flush old postCollection: 0
Adding to index...

In Connection.php line 712:
                                                                                                                                      
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_approved' in 'where clause' (SQL: select `id`, `content` from `flarum_p  
  osts` where `type` = comment and `is_approved` = 1 and `is_private` = 0 and `hidden_at` is null and `type` in (comment, discussion  
  Renamed))                                                                                                                           
                                                                                                                                      

In Exception.php line 18:
                                                                                          
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_approved' in 'where clause'  
                                                                                          

In PDOConnection.php line 82:
                                                                                          
  SQLSTATE[42S22]: Column not found: 1054 Unknown column 'is_approved' in 'where clause'  
                                                                                          

sonic:addtoindex
```

If I switch to a different server and run locally, is there no problem? May I ask how to solve this? I am not familiar with PHP and nginx, and my  docker-compose.yml is as follows: (Other related settings remain basically unchanged)

```yml
version: "3"

services:
  flarum:
    image: ghcr.io/rikodev/flarum-docker:latest
    container_name: flarum
    env_file:
      - ./flarum.env
    environment:
      - PHP_EXTENSIONS=gmp session brotli
    volumes:
      - ./flarum/app/public/assets:/flarum/app/public/assets 
      - ./flarum/app/extensions:/flarum/app/extensions 
      - ./flarum/app/storage/logs:/flarum/app/storage/logs 
      - ./flarum/nginx:/etc/nginx/flarum 
    ports:
      - 8900:8888
    networks:
      - flarum_network  
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888"]
      interval: 30s
      timeout: 10s
      retries: 5

  mariadb:
    image: mariadb:10.6  
    container_name: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=password1
      - MYSQL_DATABASE=flarum
      - MYSQL_USER=flarum
      - MYSQL_PASSWORD=password1
    volumes:
      - ./mysql/db:/var/lib/mysql
    networks:
      - flarum_network  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
  Nginxapp:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: Nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - flarum_network  
    depends_on: 
      flarum:
        condition: service_healthy
  sonic:
    image: valeriansaliou/sonic:v1.4.0
    container_name: sonic
    restart: unless-stopped
    ports:
      - "1491:1491"
    volumes:
      - ./config.cfg:/etc/sonic.cfg
      - ./sonic/store/:/var/lib/sonic/store/
    depends_on:
      - Nginxapp
      - flarum
    networks:
      - flarum_network

networks:
  flarum_network:  

```
